[project]
name = "linnaeus-test"
version = "0.1.0"
description = ""
authors = [
    {name = "Jornand de Buisonjé",email = "Jornand.deBuisonje@uwv.nl"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "linnaeus_test", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
